# Generated by Django 4.1.7 on 2023-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola_mundo', '0002_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.TextField(max_length=100)),
                ('precio', models.TextField(max_length=100)),
                ('fecha_de_compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
